flowchart TB
  A1[A1 Requirements Refinement] --> A2[A2 System Context Analysis]
  A2 --> A3[A3 Schematic Architecture Design]
  A3 --> A4[A4 Design for Architecture Views]
  A4 --> A4a[A4a Functional View]
  A4 --> A4b[A4b Information View]
  A4 --> A4c[A4c Behavior View]
  A4 --> A4d[A4d Deployment View]
  A4a --> A5[A5 NFR Design]
  A4b --> A5
  A4c --> A5
  A4d --> A5
  A5 --> A6[A6 Architecture Evaluation]
